table ArtistSongs

	column artist_name
		dataType: string
		summarizeBy: none
		sourceColumn: artist_name

	column track_id
		dataType: int64
		summarizeBy: none
		sourceColumn: track_id

	column streams
		dataType: int64
		formatString: #,0
		summarizeBy: sum
		sourceColumn: streams

	measure 'Artist Streams' = SUM(ArtistSongs[streams])
		formatString: #,0
		displayFolder: Pareto

	measure 'Artist Songs' = DISTINCTCOUNT(ArtistSongs[track_id])
		formatString: #,0
		displayFolder: Pareto

	measure 'Top N Value' = SELECTEDVALUE('Top N'[Top N], 25)
		formatString: 0
		displayFolder: Pareto

	measure 'Artist Rank' = RANKX(ALLSELECTED(ArtistSongs[artist_name]), [Artist Streams], , DESC, Dense)
		formatString: 0
		displayFolder: Pareto

	measure 'Total Artist Streams' = CALCULATE([Artist Streams], ALLSELECTED(ArtistSongs[artist_name]))
		formatString: #,0
		displayFolder: Pareto

	measure '% Contribution' = DIVIDE([Artist Streams], [Total Artist Streams])
		formatString: 0.00%
		displayFolder: Pareto

	measure 'Cumulative Streams' = ```
			VAR r = [Artist Rank]
			RETURN SUMX(FILTER(ALLSELECTED(ArtistSongs[artist_name]), [Artist Rank] <= r), [Artist Streams])
			```
		formatString: #,0
		displayFolder: Pareto

	measure 'Cumulative %' = DIVIDE([Cumulative Streams], [Total Artist Streams])
		formatString: 0.0%
		displayFolder: Pareto

	measure 'Artist Streams (Top N)' = IF([Artist Rank] <= [Top N Value], [Artist Streams])
		formatString: #,0
		displayFolder: Pareto

	measure 'Cumulative % (Top N)' = IF([Artist Rank] <= [Top N Value], [Cumulative %])
		formatString: 0.0%
		displayFolder: Pareto

	measure '% Contribution (Top N)' = IF([Artist Rank] <= [Top N Value], [% Contribution])
		formatString: 0.00%
		displayFolder: Pareto

	measure 'Artists to Reach 80%' = COUNTROWS(FILTER(ALLSELECTED(ArtistSongs[artist_name]), [Cumulative %] <= 0.8)) + 1
		formatString: #,0
		displayFolder: Pareto

	measure '% of Artists to Reach 80%' = DIVIDE([Artists to Reach 80%], [Unique Artists])
		formatString: 0.0%
		displayFolder: Pareto

	measure 'Top 10% Artists Share' = ```
			VAR n = ROUNDDOWN(0.1 * [Unique Artists], 0)
			RETURN DIVIDE(SUMX(FILTER(ALLSELECTED(ArtistSongs[artist_name]), [Artist Rank] <= n), [Artist Streams]), [Total Artist Streams])
			```
		formatString: 0.0%
		displayFolder: Pareto

	measure 'Top 20% Artists Share' = ```
			VAR n = ROUNDDOWN(0.2 * [Unique Artists], 0)
			RETURN DIVIDE(SUMX(FILTER(ALLSELECTED(ArtistSongs[artist_name]), [Artist Rank] <= n), [Artist Streams]), [Total Artist Streams])
			```
		formatString: 0.0%
		displayFolder: Pareto

	partition ArtistSongs = m
		mode: import
		source =
			let
				Source = Json.Document(Binary.Decompress(Binary.FromText("rX1rc9w4luVfYVdsdM9sqCpAEi/uF4delmU9R6myyzU7MUFJtJJWKqlmZsol//o9B0BKJED37oeth6sCB5lJAhf3jXv/8z9/uZ432eemeVje/bKT75RGlLZSwsj/2vnPXw7vstm8afp6+ctOsVMqXSgJWBA7bb63q2y/fqoXd+0vO+VOYa0pZG5z99Hrbtmssnp5lx3/siMBammqXJuC4GW3Wmdn9QJzftlRAIUVlVbKffHse91kp80EctDXDxjWO4XJy6ooSj/8uf1x0t6l4ycvizod/bhZrdtlttc2N03/y47ZKbRWpeQM99xYDnxbdlr3XZvCx4/1fbtsMjzKfbdc/bJjdwpVSSFFXpbbz+/P63a5euwemh4zKs7Ii0IW2q3Mh3qxal7S8dFGCIB47aLSlfvag/rrOrvcLB8msOEu5TlAVQEMW3i0qFerbHfZPuJngRfETWWU0YV/mr5/yWbrl0VDGNuo8jK3Vvrvns3r78vsrFneORgbKa20eVHllvB+/dgualDBTbNYdBMTPtaPIIPdfj3fYLFz7KgshNRYLAfvtYtF22SH7aJdzYFjs0o8Xl5Z//Mn83rBrU2A6LGxTWVRKCtyv00Hmzo7bZ+w/Tk2qBT4u6xM6fe/vcVCX50eAMQegGx1pfI83+7BedPez2+6TT/vOvx0ITinMCaXViWHIicolNaiKhIQa12UWmtTlcU0bRRYb6wHiNwUfkG7xd3Ton6ZgP5j0zT8VixxXhmRC3yvO4j13Ut2VN/jZQusb66qUmptjVvfvr5bNC/Zftc9kdqTCR+6H60DsMB5qXJlpdTJES0M0aIsFXZ24hAVWOQcsKiMX/+P3XyJM3zfkJgLrLKwOgdzqNyPXiybq+Zpc7Nob8E4sL4iz6UG63Ab9KleYoM+dliDEssrRCUqqf3m7T63ty25TbHDNcBo4b/yqn7JDurFusMKlSVAVSrQWOHe5eql5tOAX02AZ/Xtw6J57PpmAhyeyVIClKY0ufGEcIK369vbB/CKxxqrUCpMwPMYUWjlT8fiGatEWnU/rUGNOHn4fJWPqTSBLhbtc1tnVx1+4R4HqzSYYMGcK+UPQDLBYgK2R2KRq0lOVVaYIUWpcfzcmh0+An8EdxYAiqrCs6twaPFSeOpF9x1ovkOeXsrKaPfLp+0iO69X2R8T2HX3mF3cgRcAK4iV2CKcgDfOulg4wpdYaSs0nsQIOV4LKQmBDclS+GWq9+qblwng428g7AX2TWLlIV2EEMo4Jr/b367b2+ysWz40L/w5rK+xtgSrlW5r9uq7bG+zXPJrsbR4/FJjZz2HmNc8Mf26+TGBnkEwdMtMAcKSG/BanEO/5Ptz7DN+dNGuO9CDrIirAntS5NHKKay5KRV2yxidMlqFhQXDkSD9ym1JIR/uwRpA3QrrqiuInAL/uI2ul8vsoOUvJth2i1VJAPyzEIVboPN6DdLo7u8nsL3rGUYlRwsQZeU523nbP9dL7I9SRARJvRjRkcIig61ojR8P3Gez7MBEuOEK64jtzq0p8yo+WgorSf2gohxNPlkRzCEmwbT8Mi4fcKwu6x7SUGMhNTgLBKJfyDcOqrGIWlh8uPRcK1JZdOFwIVVRuued1Y/Z7LFdQxJpLorQFWVDOaZPzZURCoJbCfeLh2Q7GVneBHi5rDcTw3z7SxDKLfUZLChOdWGE8c8xeAVNCMK8AmOIV00bgpB4pbHuDM3+3MUo1lIZBY4pvEw76L5RQq8noKG00lhmhb8gCYU7Ikeb5So7/wdYzIokaQRxHvXKJrtrsNSQ+kAr/yhvp8RglbG1PHm6Cupa5uT613oCrX+dc7h0w3muIFvdgQZTwVIZyfEClGK9QDjq1i8cxxJK5fS8ys0/aR9v+noC2EoQowmQPHDK4pU1WFnJN6XgCa/T1nOsYk/NzVgPm0qWakqnrIhDLSTFew62bJsFPt6s6in8qH1uKLkSYH/eLG/nHbnRonGi2ApOEdDfrNewBpwswcZakuUmlVVekSu7x872nIQCxG2A+C9AHVX8rTG2Pe+WmwSKhr0QDmbX32UfNj1fxXKnwJEtuK4Y7KDlhggwAqiIjlJ2F81tttcsv0GV5OewL6XBl+a53+Gzd+/ce2NL8Ng2F9KkXMBaongaJbZHCIcLYtFiRUtwBmGN14dPf/v028TwXvsDa1U/QS0XhDT+Fl7SQu96bu66CeS6fll0fTb73n7F6apywpAHUL3V+OBVWMKSpxham9vXs9ZpZS/9hgYC1rEE56R+62j0PR5l88BfxCJCqYLgl9JE21IpYmBtZeBQ11Asp8aHh7zi6oqCeoAN67SEbnTUk9lUXGKRU5p56RFL0QqrDP0G6k3xph4ddZ3796Bb0MCosLIFrAewa2H9KiyzC6cfgRqA8dBIG1SJzW2z/NFNQVf1XdvNm9oZQzlB/HRZyHLqwXKBBS6gauAvb+UNFioXJUGsiLClTkBJUODMyaCcRooVuCFmgMKhrijjf72FIOSiQVhzguYETCkDU9oekFxgRSGbQBTCP/hVO4e0plkiuJZ4WAGeWk4oi+mEjxvs1H6/+ZFdQ+m5c4/GxS4FKMcqdzQ/bEBYy38xYSDiwOcdqI0KJj2YZnbZrPt6NYUmCiXO8A6lDxh/7jnDaVPfb5qs+xp0/8lJH48PpoaxpzUPeopM/HDx//LDxU9/IUXGO5qTYgqqr9KWiW2eoAk55iSqnBqVyYWXH8sNBMD1pm8dueekKfBBS5PKuzZ+w/u53yY1gegge/wRnS1hvAVdLUWvGwjg7D3Y0PvGiWLwTUzBDJVr74pRIttvlmtCpCkoZzi+nkX98ccf14fn17v7xxfnxEku4NmCB9gJpouDP//87//+lY4Dwc8LW+nSmw9/1g+UilPQNbXLs9urmi8EG5kojLjK89qrevM9A9v/htXuuRowlPFiVktwADMhT0GHnIDjvdWQgjDB4SJQ6gKq2psKhNPohsGmtXLDn+f1498IaK59BY0eR8Odur5p7hoanPsLrN93PHifXTXP7XO94HzDzVTQOLTXmJxuDAbHYVhSxhZBP1g9NHfZ527xlXBFIrHSyNxv/173eFNnh6v1u3d9wzcuuWKwMsFR7JsUnwIuSPht34DCKFYhKDghd0ax+InLIqd5jGeX2hbSW3Tdt5bjXEf6JGTpleWrzXqe7f1GiCtJ4wFsrIzVu5ymLRYOPNAqLxpwUPoVWPtvl3X9MDVj1i4eslm3pI2fomPRmdP+5ZKVNrDQPew89uEvKoM5jV+8sSwhJSuvTz23d9nRplmvJ/HYMs9pHZMawEy95PoIE++qu32Ywk4azyZoMIOoaU154hr5LXKazXgdyG3p7aatYy+nWQxhoawovePHU006PFxi2stCwwTX2vt7rtv/vRGi+co/b/yfd8MRfqZ0nykltZKx5ZDTWoaeVWmt8uFDJMORC462NJRu6EYiMZVz2tFQwCSOc1A6oFpygWkmA4CoLqpXTxoOV+0s4RQ+gf6f/X47d6IuQd80p5xGtpCUv9LrEyfkLXsb/6zcIZC4gmVvJtyCtLJFUcLoxDdP8Dua2aKg47DwSuoRyJJbT0NaCEOflf9gRK+wmaElYR0KY7x1uLylj6ne9GQmnCExAwdO52UxOIEwnqHOKZhh0rsEKHcOIBquHOXAhK4sfQ1KBI16tc7e980/N/ja1r+TgaIGPRfMtgh6wwYy/bZbrydQJ7jqxdo5XXAAicIgrrzCPgOlQ4PekNXBzKYer3EIdORCjaGtuQKTdodiBo/rgbMWUphfBtO7wkMIcMjcMwN+DwzuqoSBiA1zo5dzbFezWGSfSYP1Ix8RhncF/oeV8O6Wcyg0VMbu/RvE8NAvHmPeHbPXd9/ds2JDiqrSoN1ghi6cfyuH+V3RNQnpEvu3YIYBE5BKuTe/Z2vYAtjmW24W7G+AOCVgsyO1D3Z2hQ+ABoIDq3XKWDw8PFiwvmkeiLzyZurVu3ePXDJY3RZ0BD0hmPiQe9RUJiCwNPrav3SbJTUFmOSwvQTMau+/OamXL1RiViQTmN3gtJWzwzzYdwv/rSUQGjjB8o0IHwa4tYUtIdF9hGhBQ+ZgM484E+xuC0orjcgjWwiyF0ae0hIagXfdts5rm8Poto6UlAk7fz9f3/b1d+8xTPCzzdd6VWd/zz68PDWP9dRXHHRPtCqbCei0Xbn1tRzWhdpSsLc2YQTBUoX+LuS0uxUKDSYI2DilSqM3sLQtLG1llJf/RZ7N6uf6vpnAzqBwd9le1znzN4HfFEPY4UCg1AgpE70wBvfb+7qHeGTw5St1mlnzF6dhdyU2EaahN76bvlsFcwAWO+SvsmD9P1G7YbtjhqCfTkypzbDdbSnBaoW34bwyBsvdgnEUryS86b9m+5t+5T6C9S8kBGjhPRajAwYr3UJVLcvKq5Xv8UMP2cVt4zYb5jjQogRH0xOUCnPcQjPNK+WtttSVksMsBzOAjVN5N06imMYTztrbeQ1mvQcdICJ4GPFYGbCeytuYkSSCJQ8YhyGYt9GrYGGxZjCtvfs6fhWsK7RyCEC/DpfdonOHFRY7eBMUlNKL6gHPhq1OtlVpsVWo6tt59qHbuGWHlW4Yb4DFOnHKwdQAa9BiMJhj6seyYgIOt1bW8Y+ri9nu6TsCBQAomFXpTaNIuyhgixv8pfHLXjHdAF7X2adm2dzT7ixgkBujqFP5WPGASyZYcHmkn4EUvqt9EBmm0A4omtEtr6Yd1Hd3L9kXrL+H9Y5R4OPWhCce/l6ExeFO/B4m6EpsfaKj8F8Mfvx0cshh7IyCsivVlM5SwGQ3kgsYpNhed3Pzkn1oFhSPMP2A0kujPB3tP7hYIWxmnALsSNhPHKMn0Du4DmieYYwCNq+hE0QGg/OqW5FWli6IWRKDcSW9WnC4WtQ30O13+8eakguWKiaoyorc64yXzarLLqF31BPgafvjh/sQ1r0ooT9LT4H3bb/IYNX1DWOCMGSBCgmOI0P846Ht3fdh2RjhVKqyY9dcAr05MME+AAkLRu5Neuexzfaa26b33xrh+9A9SJmXGzI/fClhLE8h32IgyehHiNbspOseJrBXEVrAHDbQKiqop54am9uHl0lkKDQK2MlGKMjrwH+PmlX99WuzWK0b94YxDsFR43Dd8u1gQUNUQeYLbWNhDxYJsKRnzxPc+Ffljsbe4bSHVxzG/qAZAwWhqsIvuNPjwJJ3GACCyq6r9AvNDlRFQ0Izk68R4cPzBrsa5pQwdBdMsCXY1YTLQpWJVwa0BFDSXeW9HvsuFveNSL5DQxiHzqc83Mln94ECw2DIZe7lx0Hz2Gan3TNMFqLljjYG5GuVGip3YLUA8BBVCFi8CugEgcTpPdeD+auNNKYIwmF3/2r3z8MJ4OLHht5BMFCOg5sF/9H7pr2bGN59bpbrjaNv2MBYVHcIYx9ngr0pYzifgArNzB6RLmkEjr4Te2Fgt6vKL2oiImAew8YEp1ee4ewuwXXfFH1o3MAhJYqgBkZsGeYwPg0WEdjgdfvu3crtDIxePJKAee75ze5zPTH6ul8wePEMTHgogzIOlcV5phLovOVBhQLtthOGMCweHCstg9Phx8vEMM33+WOQB7CPYVczKyFEqLtl7UyQ9dzne8QTzvrfTtr12n0xdgkM2OIfNSBTGMAaOiZUGTkVaypgA2uYzabcKl2Lpnl6yea1N2+wdcAlLE6pouBiAfOXoVPqSFNaAIxgDT6tReWNnzcOB/MX2gHUwPI1Sygw7xgJKVsFzGGM482Ut0sHGnGCDckM9jI4E2hIeBsrVtGSCSMChjkNC6eq5DbA+725w4n0alB2Vn917CyeNf4KQ9DQDV+kBnsCz5pbHngY2jp3pmGRJ68UYWedX7loeJyAAxOcKUYwy7ZRldcjHENedME0p3GCQRmHCQtY58AKl5OXJDwkaEQVMOKhU+ZYq9fEhbD3sL81iFDD0K0m9yqeELgaLHMcXCjG1r/54SPkdjsHnRLE/tJSBG+305pNPGMqhwt2vKpcZk4Iv7fLlsMGwzqHYliJKaUhxveal255O9b8oXbtuKAf1KdiSPIw6RlVshCdXmnqu2/N7Tq7dLsWo8MDEWPbb4TFr6rSea/9m/b1M4Rc8P0k8CWI57HO3tfOvoPM2FHWwhwq/Gn/QqttQaAAoJjo4JWHsC3xcEQHpgQMCLTv5Xj38hk/9Lt/UgkQj59D6vhHWba3f8t21xl356Bd3ZIejOIsbLz01uibKDXYL4N3Ublf0+Kyvp0YvuruHQ+Mx3fbtUtVKWD1K9gjwljvH4Vm2jpGHQOvS4zNNCVMzpALM9yWGJs19VfY2ESwYRCGeBMfZRuFdwuLfYHmxlwGORZlMPaVxgpL45PuTup+YvS0vunbpdtDmPlQ/CuBRbNTju4CBj6kIPRBsxXZMB5OGicJY2z7zjD8lYIlR6nm9n+z9hIwBq4bJ7nj4eHzYUeVtAbrJBJDwWKXQExgSd619AXK9OnzrbP6YmzvdHf/5PL4/IQY9krB5mGigdckWuf3Lyw2RMLiplfd/dqiXjKKUljsB74JBqHVAyupEhxWsLO9Hb37xz8OTyfGD75BCfjbBDCSDBW2iel4WIaJjMkYdcHHe3feKmxiafNc5VUi72LsavcL9cQKW8f8SxCYE6vCiIyMt5nArj8cZrvnfxwfXn8his3C0kH1897NrdszAZwnP+TTJeDA0KqwxdhnWHUiuOm67Kjub50ojcHRq0XYny1MzL/DSF8uu7+IgwQKZ6h46fCxW717l71vXLSlqEAEhRCwmr2DK/I9gdfsqNwaKDrCplsVgQPpWYFUcm1gOWwjeZ5aS4G9zxkpq4rgeb2poXmBwr7U697NwBbjCyF4fNoGyO/lpmuZJbRmjqrAXoKcmXcYi+BSYNMYZcmlx476zVOXve+75brxXx5NOGvu5/htsPx2yZAKTGdMACuXlXpVwLGB1z3VZ+wdUOh8b4lEQ3MXuiJgLCb+KcYLUgqzIyEqGWMW4ZPQlXbXOFtrn69rMcFW4CReT73qbqCPzm7nm8UPwhVgU9BG0xPPFaHvIUxeMvcn030FUG1csME/1nODx3psXEpRmeeE8Z9SywEDgwG3I6FzSmV9tGHLwBLA+cYhgjb3E+BYvpV5CRg7p0NM+gQqPnj6ou4fVv5pJCaQogNzYIy9rxfZvnvRXAEtuD9ewAwYWplrYrlRW2cDr0nsUuiWOVYf5FQZ6f3m3m33ualpQBDH4lsBE1l4j+R1t3yBPP3hfhJra3hZQqs4hyvBvIyH8YVhnrmt18TpounwT/2eZYE9MbAi8O3qzbE5g5HlD0mBVYa545QZ91C/YYXrJUPH/7HBQaH8TCf1LiEJXA3juc2h3E1mDiQTTl9qcJMp4FVG4Wd2JE4lWE3QBT9lR22/III9o6M6D3pXyDIoC+3GmXlYTT8Gdk1TCSz9B89r6h8u488/DXYN7BkWo7eFj+qbdt2Rpy6a1Zo++IlJQ9mZgP5eBSMfBLG5YF9VrqqwXff3LzRSaI+v6okZQ9IosdnQcSHPQ0KBD+mWZc5xCT1/IqKboCHjH6vvMvCxoVrIqghUwc/SqdQ8QsI8Pm4gwXGW5l3b/2QyeOmKOTUXSy6TS7+Pp33pHjriE1Cg7hJEoDCoQ5omI3u//2izT01PqitBCDi8lmTnE1pw1Pb6l9q9AWhB8pqF8d7Lk66/m7vEdnAuQNbi3UUU2ypLQwis1XpT9oAB1jPKA/ed2ERJ9S1Eo69+FuDnXOwYno6xKe/OmrcLZ7se1Y/gt3xrKTiFuWX+rUfxzlJig0qqkUEtuHperdp6EonJOZ4Qk7MsiAsoxF4CjCg1BiO2KrEnzNJjEqU/Y/XKkajEbuAgMQDqBV696Tv8IsjA+VaSCc4SZGItDDYwm/bHxJxDhuVx0n51XzQx4Qq25I8Xp2VMff4AK9Yw0aTvm37qIfbpE6FH6aimzTExY3yFRDlQQF1zu3refP8IEuHxl6AqXqChlhJY8T2I5zN5hPtekBYNwipcwfG7fdW4tbPEFB2yduvIarMzPNc3oiAlGgyQquJNF8j+2P+Dd1ZARDDXLNM9PGP5K/vIu3tTWEca6Pr+ZQKc1d+bZt02E9CA+SqQVqELIUNW8J8M1LzUE8hl3/xouxUXXYGkCljF0Em27LN/yS6pK02gp7+f/e2PifEDiIaXbcgNlA2U/sv87XbKVd03mACLpPU3ZpTkJCb9euXw/PD45PCAgCIgmMgctMYmO9ssPOOMwW24LgGGXFhh+3MXEcmDYMcrnoL6SJYKe++uCAS9KIqqlQr7z/RZ2Jh5IKvg/IdBCig3oIxwL7PvXhrI52e3Cho7JcjKSp9z9KFbY4t/v1/wkTR2RFAHDhSX6KgaK4z9shCLr4z7CrTDsDPhkrDWMi+nOIGWhLG0IcjIPJTs7Jba87Jxv4/loh9xm+o4XC6tiUFUB+/y+823ts1OaqcIaUMQZ0mqkUGLNwGQCzxZiBGMOGaMjiPzCeyi26WudkoedQYeohNtBCAMMxnT7xqUz30Ie15mKk0OFNw7L33GhxOgzpUDXRl/Qmf+e/YBj3fR386xl27F4w/B/s8O6h42PjQunyKTzNnb9Ivs+NltiSnGmLsZR9bomJspgUp3WXLoav4PJhW7T0vgWHSYHd4x0fBEXdfPTGv8MTFh73RicMQQjdqhx95RWRA12YlbJ2eIlkbvlBZMMa+Cyu8y/042q/nSnTVjgBtlts63o3nnyN5YjgsrwqXCvS8XVxzGbkGnx6nwuQjHj/XypnmYQIa5eaUVBBUsKmmnsh+TCcPkxwTca5z6C8KipwDW/g49nyAifzHq9b4BRonmOg/3qUJ0CF/GL2VkxvORVxdsglwu90KaY2klIei2RZmECEuruNQlU6CSMBBMIG6iYYqtGAb7E+AtUou1J5RX+TZNua3vu+zpx8MEdtreQMzeuue3pEKsRVBzB3dbQQakXzCyoGR/2kB03LiLl5XgaRM4hWU1uqsG2uLBZVzFh6liqVoVO+5WCUSvt0ch6n9AbW7u2zv3+ZI4LLZCT9vp8YTLHnrAIwFJLgV9W4vtrYFv7dqd0/kU/IjP3UD/nNfrNRTRundSMZ42ThbAWSbMG4YJ96k0ObBk0N87+WsS3UHTb5w2VRkHayjHPj+x9VyushwHWzOlHVNjVZHjQyqEi3ax2iiFoKSqYPN6YbKlkwQ4Pr8+vPp84a5gg6USVPY1gkK2KoUrN2AYevLL4/Lnd3k9VJSUpDgwuc9hH1/XjNEplz3EDmU7JGLgKh9hkEAyfSCkCEGjDtGUoW6bgMMsVkh1gkKrwmv3u4913TPOmCC8IfoyMe7O8fIfmUuCWrrvNFSMNEl0IscJT0FliymPIctuFEOVoqLyZ6QOabXDS68x5lNXs9kT81f77R0RmQtOg20YvEH/f6dFr5PnVGVBr1uvo0uYgWZD7Rj6jQ0G6ufjfTdeUqGuRBlUG2/1yVxyGJwuBMn3Nqvb+gbKGXcwV9TQQWs2yfZJsOEtBplr2i68dB7yVZxOS7uvx0uuKYygv9H84ZXZwGK7u/oh21vUZMAyt0R5aTC9Ww5uSJNPM43Ga/e/Qa4u7x0Tk4UgKA1eayqpCjolbUs6B2yyz0VBDP8JunhYpKKkiVswf06+ecbOWt46S8D9roVp71wyspDEIG6NnagfIQtFu9pgis/EOm+W4Pvv/U3yQtMm51V/o6JDHUNeM/vY8J7uBBin8iVThpfUC0MPgRI6pGpeNYsVwwTYKvoxVJ7LkGrFyCkMKfpE7OvloBEHKLkVAuQovVkeUXCZ01VTCGM8gzgGZSyZcQerj24i7JDwuQa7l9nBnJbtcgI82oC2oGJkR627Sh/jI9IpS3qowF5tOc6UkKWkT0tVhQzJ4I6gJ4DTDU1JrOeyb/+5cXy0VHSiSaV0FeLe2e5de7tun+sJNF4G7WCoopVMg+YJ7Ne9NDu+xITd3nd7TbZKsPfH73ehX238AkTgWb24cz9j6VlkCr5PinvNX0gQR23Ot3+OI+tWvKLPFIpliChSJ2UFAsFhpaFOxFk2UuYOYwrSa0Yw9Mef+3jST4xXURb0BxuXAOsUHo6VHNNFkeukjoGU9Frn+bYmxghTdHjjc4E1RcdWanrXpS1C2sbQUS6lIeiiq3JoTiXA0cbdbUzGvUiXlu5/rcrgXf3crloGgLZxaMhVToD9X5lRUmkC8OL8Y+101/3O+XXA7xm5MIxtB2MSzJFBwgS5gDTosTEvd+7oqXzH3SoT4VkHqkAMHX+i1FEFoyuGqXaJBFElMa1E4d2sI+6nJIM2eU63SPLBBINJd4VXc2+gCPIWgp1WvOIJo2/WjCVBbSu39Y3+mnVnTFKRyjgIquvwGCpuE6QF7fapEDMkLkNfrOPj43Snh9lsdni1+/6YrEVzuXMB+yNkt5wfnnCYawltrgwXoAdupgQ7vIPqcLb5FwdHFzv+KkcR4nlvxUN06SAIci+Azhrq+ziLDaid+ZJu1+NZo9gNmDtDhthf4yXA661dqRUjkWDx0Me9bOAx2u8euQ1aM8jJCghvnr/3MBToQpy1K38HJ5l11q5v6VjOdl/6ZpXa/OkHBglnYB0EQabCr922YFICjKSYtgRzqMme8Uzw/3jKG/PUFePDpatr4g7U80t2sfSJHf3mcTUxZW/TQwDsda7aimDIGm+linKbLvwCNWt38eRuakiTcwKOQri4gvd9927R1q44Srd8945vYEgBOewD7SNGHzY4aH93z5dAY1ZnuPXMjCq8QnR+fMIKZYZ7Lpj1VEwZglArmG8ACtXBxTb2iSe4NxTx7Lf+S7iZ/os0Mxqce7yMGE4MjWvCSGMczBoCKr0FCYWMaRSGimIoS7Kosw9NcFVMTPB5yR+8ihGDr0zeVK54mxBB4oy9YgnM6/7XnYv5TqBeEljBJBJuQq4n1AObE7Z5Zf19YRdECeWbcOQJGssre2GNmq2aZFmEDopZFaIvu7DOZs163k5gw6It0koHMtcx3H1t6YOk/eIcQOmEAYe13HmoH1WuE+3baoeB9+p87AmXlrsJktneWR19zDKnCKInOFYOeCUmO5pjp0lrtnJwbsIliqDTx8MTYjKZ4lPEzurHdhLdCtGf/GIlmBXFS3BbH8djvWyzz/OWnnlZ5Uy0yvn2Os1Xk1XBzC0WwfMVPUZKRwxGZBfDpxsIdazRKbGS2WlVLoMbM2IAlSQM1VPboUVUKQ4LmHc+bkUB202MM91hYthTdsVqg0yNlF45GOUEwdxmFp7WOtSvuuporl+1t04cx+iY73GCZUaioezxMeBmtWrBXg7wfk7DqCo3Afb11sUXeLYSgjmQzAOW4Zcfm445lGuGnhN4XLVPiZxZltayBserIgQlh6OKSRJm7HuC8c2sTpCLtOJnLFwJyYxQy+sF4b5D19835FhOCGV/n5jz5XD3msOKwzClg7vyeNWTFf+d6efd4uvXjnM050AlK0OuvDPWIYUX9QR6Wq9W7lMs+Aj5LsqQ8tZvmqUDuPgwFHl7LnJoJtjwFpAS3JQcXFB51vG+7Zub7iU7ODudQGPOo1jtUbub+X5Ph8mxylV7tLBR9M9FpXIlH8lmRMgkqtu6r93yxtDQn6VcLUjoWHQthAj0EipE7RL2FCs9KoakSh/7ieuXKcIuaX2UkqNYyVGBk1ozdbFasZKjKrEa1oduTjebO/cx1tmE9MtDXtw+o67ZB7okEmzASRUrPGJphQqFEA4XrCtDr03vNMFkwpsPW7HyI68q5zbYX5AyEPbZ7nLt/29iznXdbjicc1hYnNVtvZ8u+zYB+KPESpEQ7+T3enCFSrEGJGO6Ve6Fnb9ErlgC0uURhNs+A0tZscIjMKN1FVsZikUevSMt8u0qFnjE4aecNsHav6yDizsBP25WzdN8AnDFafbrrxtQ3gS89+7dt6kf272Zt1CAaieo0y+db2B87DUu6qxYaRKnVrGaiHuWZe/ySAhVhASs88Djmr+gRzPpEortZskEM8VikzAnob+He88Na+6c1DXzfxTLTcJMZYUs7/N4n81ewDFcAT1uEfQZPNdUnVgwEofDhitDRPgWKg31P75yyR2D9WCNfyn6hfon0FCzrmlA9PS+1+4ZuH8wwlQoUHK4aH+4NJ5mAjxgSg2si9Pu2cHcX4hFk8uJMhmq5MqKKrehVulr2ChBnMsyO3xp7rLLxh33eMYXktypC6VD2BAzmhURXJGF+tHtf8kNAYnKUGHtaAN7dj4BnEMW7U2MMyLc4eVggPIppXAwS7f4WMhuNvv9/Cj7fMFiDhBdhJUVYhTRSMajKoBgRrzNxI0TcT1VJUvegqKPXU7mWyspeb2qBAPw8aO9xV9UtJLxXShGd7QE2q/N1OdO27UrjunWRype9WJVYTt1LSHBh7Ioxs6P90+OM/x5cXo4Ae8ul83yrH45cae9ad2zs9iutu6mpS/3ABAk2D2sJtAvm769a91jGYcoEy6C7jLfuc527zftwi9WNGGsmEGTICw0bNYqSplUsnIFgHl0bSrNleCFPQuWERT/+767dHecEij6TZUTxokpvML28Xh2ccFxEgXN/FD3eRQoV4pk4SK2PqAVqgbg+TjO2j1VYPv3PRfW/RJXPocpkOch6nmKLzxpJqDz9rbLPgXyTD43dLcopXktErpjqKuDI+++0bhhs1VvWIAt233qnNNAKctrmDjM2mxLqrxkl4HDKtZE1rwc7n1Y0IO9ahQDh4+PsNubBR9Ss0iyojruXUnbBdGsj8xqEqWUse9CaV8fGa+2VUxGRbIS/GDz4H6LhZFL2H+hZENE4TH8eg80QWaw4O+Y6TKF9PjQBup1xsS7ZmLOW0K/or8IVASCCPdYRuZaAkdpFQkep1UkE/wls/Rn6wWLPKTjLVZ864ZMUJgfc/+qE2CkndH9xZpwEDLlK0d/7rKztvNvSmqkPhsIi4wre9/0S7p4f0xMuPgL+phbXRIs7yKGAtJOvhzBXnTbQ3plunQVZOvLQ5Ndd9+dQ03R2cRaapXW43qNCTKsmKHoh4Kgd4WQ3qreJqNuLyAPl06Ox3C0PnRd5bzSqrZZD7xmpuiRyiGW6RPzvqMXVz9H0ReVQ7pA7fXa43e6CanZ0x2Vl7wd7/n0KIs+QYdKHh1RLByYh7J9s3Vfv1BVcUV4WeabYb3Kg5ezLxxlee8CYjUPuvzGCb94+PD8w5fLQ4paOouo6GwLY0W1CxXdPiwjK8xrlZiWlSI3YGnL+4kJkKureZt9gZ38g/ozPUS5gFUSQjq7i2foWdlBW5OK6CDyF/48m40d4smE1EWp6EcSvDlU+sSQN6qJkbNb8EZI/eXcoSUrODhHUIgO4idhST8+1e0UvnqCErV5ypaumo2rMq7oTWIGP2Nw7u2ujv+8ON+9Pty9mk3A47TlBH6z8umJYhmRShfV2Nuk6IgSkL0i3Nn66FQj+qCg2rAkuJ3IjlH0Q4mSZyh4tDeLjVs8VnSnq0HqpGqLolNIQBOHUStCVVhXuF7RHSS4MqEWZTgddOXw/ua2JuHpr0e1y+xMkFHJaHp5GKUQ4frGwHCjh0ew9lRRJL7vBIwUApZPZfaRscE71Dd3dy3pBv8lromXVm8vC28dBKyeWrlqt2J4OUWxaCprekFpMNGNwgQ7XLA/AOxvx01ZSrWyLLsrIk9xAjmF/aahlqVZSpXXHsqQDD+8mJmAjvHXC156d2WvWWq1wk5tC0BuW26wwGrFXE2tk0InWriy+WAu2pupYz+fZolVwNj5Ir7qmmBjN18CD5PWNAuzQvUBIfpkxnFxtwQeVbbQLNoKIcd2Jiq6jKhZtpWaDFQeL28gPhlR1qzJWrGEeekTLUZaaIIefMt8GsN551LUp6Zsl5f7mfNWQTW88atZhJVV5MpQ3y9a2RgermyMkYtcf/N10bnJgrdzPY+K2LdmfdRKsOpDXFYogYY+2wQ8h64K4/zJf5JEIljRPiQ4+ywezVqpllGH3Kc/js+jZqVULAqT+LyTuMaSrmESf8lmm+xwxbp47uvZQcFWzE2ZTFZOJpzV6w3NVM16qdYY1rDJfVx6MzE6MRQ/qXWwgMrtf2A/c1bD7JJg5UHWwPRMEQzzvatbl2AUOHX7XGd/zibQscqhWXuV9AQ2oqZgdmgALcitn7Op5xlLKBJjhwZXOcFHIIadUTRLrvJGEP4dePw1C65aGOrFVsOJfo67xWttOtdvKrtm2VUMw/DUobvFPX2UYKm8daFZZZUNZ0wuf3azI5kT3+xIJkynoGmWbuWNHx0KO5407eqFpaKeQSoPJJTC9cmwwmjvXJ7hHSASQUZzXz1Ls0irZd5rqE3i9XHN0qy8R1qo3L5dpkuG/ZVezRqtVpYQX8mV3gTzVp1m+VZXdWublzWMWiforL2bb7Kzrlu5EpDuUbh7ZcGrdoGdNPXK+WU1K7TaAnZk4X0vw5sA2rUnya3LLZnYddecJC9hGoUyChBUdNuQJ7i+JDmTovyrHH3npqybrzWFv3ZNSZhOEaq6Q5BBt4do8a1cEnx3eX/fMqzqRKRmDVZea6xCCkOgUlZaddUNpY+fRZcSNWutGogy8KkqNdg0y6rCoIYWbdWAiuPhV5Ux/cDI8aZZcxV8g74rvXW6/Mp3aCbAQbJdgkXr7tqeuIpDuR7n02nX8IRVTyvPVUcmU4KOUmgTNAqFa98Shb0gQqB5qAu4piiYIrc+VDDZVc1c+B/us+yJol0APg9MEjz6fgKB9OQ9H/ZNuKNG0NPUTmdhpbOTCeDU+KuI2nVaAQcsQ1H7g4+sneO+9P2mv9tAfjjNPpm4F5LSE+Bt312bFnDDalt/L4htlo/FvuA0efMFv3m4uu1csrpmvxVsqWB3lbAEZ4fnF1fZ7OhfoR+uJtDYH6nZtoUpS0W4cxOcoJpNWwwMGhNyIEeBSc3OLaZw51f/LGlas4MLex+BN45UQzZvYeuSwoZF+Ojae9CMTTAqIb6ZTwL929G/H/96QBeOZscXlkKEGj76JfZ6YZmzbdXCoboTY3vNAqykdjzfNYKB/gCbRA4XxTWAYTnaENVPrvhr1wYGj8LmVF5pYH6N41yupQsWZVsJmVfAQnEaHjE2dWGtZxk8/h9r/5PskQORKkO7uE/t7Roner+96d3lTM2mLjhEVLWjxhRauy45dGQWE+7xBPbdYNjWhQFNEI0IFxbJ2MHxGP3l54zroMPmUsH+qjN3130Ceq1kp9nwBewVimuVFPpIwKgklTa+8Y4EB3FnFYykBmtZTkCnG6h3tK+0cR15RLm9bk+enu0TkK5HDiuHlNNpD8kU3o/suvtsf/Ew9QX1DTs4wepf1XetyxtP5sQ8kX1mWJ+EZz5djwgcp+lrtqJRLKoaEpaCuGETGlaV0VUos7J5YCTr8YbkZVwrH6G4N5OMgK1klLZMdwmWU/u19X13yEfZKkZpyhavjc92Tw+pbbJHjALxwij1eZTt8oGRwDmUtRV/mN1gWCLehnvJ6YRyPOEYOuXsyTc6ijE8dVtnF+6HucDujr2n02+/wnBwn+HiYXlUqMEZmhxxzRSTScuJUkgJvOUg7CKj2GIk94d2yEFibEoLZZ8ZJZloafKp+8HJhBnt6tXabQmbzihZsqSSW9s/XXkTdl7iZsicref8yW0fwZdfg+manWUUK5+EW5qvHh/NxjKqLJkU5v2RL/TcaXaUUVDyoEBWUQuoGLrePfyye+6+iztQWCavjkRHMj6yo+kvUUIJZvb6hkw9jwwXi64SdkmCShnH5RMs8jxpelPAJTWL+r8lfmg6TDicBw9XFIXV9ItIlrUNmcI/y8Iz9IOwnIMop+uvJBOGSo6hl0TiDMLamEhiSOCz+vGmc9cafxBlPyVNr3SgoY/Z6ab13xtBbwpdAo0Luhi6YKTm3dRSjPimoQuF1kcZao7uMt90Ynzv3cQgSfS8WTO1knEU93Kuo5aEZMvDXXPsWfahCyujXQcr2k9i1KLPCNdTC2cyD5kdUAUONmzelEBfLnZnF3vHRKzrPQWNxgugMzbPXPdN456Em80+R2GL9ufN13Y5Aey199kFFR1Dp4gsBKsy+UIRZycToydN9uSSJutvrvNZjAduYuhH4aVtEfr/DbhJgp3WzrYw9JFQS8mNiG85JJir0fs5dLU0dKBIGPIieG0+1M6rvt/BIlquJiZ8aldg97+CbB/mru0YXS1S5BAZodj2vF08sRhmNwFCUYCswAOc8Uy0/dSckw3vuE0A/qczCLqFs/Mmfto9FH77+Vs7PSWuKGpy1zoMKkDoIzO+UWno4KEbRIeWcTM6Upe/fmQl9Al4VHnI0LdTVhB/4UbguvG7xb5iMIPKcAV+ItHM0EEDuw8mQighHwW9kgnhGq+h66ZkiUa5vbjzGsZPsKu6fQSX6xgsM3TqlCzBaK1IHVGGfp3S6c+Fes0T5Dj7jGmmvYtwmG7wLmf1mqLN0LMDoQ81JdT8afp1xpq4/QQ40bnB0PeDObAMvQM81JFJx4d1ZBJ0eIZibMSD6VPiLbMyJDsOE3oT8OqMg8b1b8vz0I7z/Oz4jz84zk1WUsrCBk1+/ujKRprCtYkTrJuzzYtxccAEOA3ZlO6+nqF/qJQFW4p5ZfBv9PMZOoIwTGVmUNTX0NlT0g2t80EJ0WSYNrr77RgY3TI09AJBIVBlKPY89MEm4MBRk2D+8mU67LWC9KuGDgZDRxNQGg8TjgtDZ1PJBlmVZ6jnoNAahmHPlgXEuX0wdHW4xDu7nb9717O2gyldkzqZVzLfmvNXE8Nnt9mnllH2gzo7vu+bbzDy3Qq4FnYl1cyteX1dt668WILhqz+3U8A4X93QRwXJwFtcYuwuN9K1tYOyVSk5paYb6VrblS6zKvRne3IPGgNRYQRDFxYLyRgTCoVBf58dECg9sHVODi2RBPyJN91I1xUPzKeq8unnZgMzll7M/dGM9DcjXU+8il6FUc0AI11LvIpljs1EQQdD/1HBJpbytb3NMDZhpOtoJ3GYxk2XEmCKRcVzQibGdft40/QLL9TjOcmrK9cYr8h1METH5y9GXYKnoaOIWTwgk3yUemfoKgLiEujGugp9PUSKcDvVm4XJ8DBzLAGjzLEE9/pPPHqF3Wj6BxeqT8DDx3bRTn3XUHzFmLvPdu3CDoYuqqJgZStTjKPURrm2eBUb0E+kVxjlmt/BsgpG77YQqKFrqsgZJ1KD8r7J8Kv7IkHo52ajExISHVNFLmCbhKB3s1rU2cdlP4H5wPdu53fGdc/z1Q2HTxENn+LLuvqfmynsY9ff4Ri9b1eu3J+hV6sQVuKQm1ATc85YRTuBvW+Xy6ZeZRf/2O/wf7wRk8yR//P64vN59m8wdB5Zhpep5iw+eNn+xdTxdytmXy3JZq6au3+f+ILr7glPlp07hSwG2UaURSY+tZM/PuqwS5+cq0US7gDt3uMsZmRg9MrlvEoV1sQl5hh64lzgpvTlLHYf5P8qBAE2rrNQ0IJn8zXfK0Fer7MkyIAE6bfLGW6o/JWWIKTpt6M2zwZ56buw/xyseBa5GPouDF1y7PdQBYn/Zg3FSORPMnTb5Rr6nxZ5knyfoAffstOT7I4tBm/fvfMsnL47euFk8KRd34Ln1Debxwns8Tb7Nm+cZZ5gZ1PfNeqVzJ1UpYYBF+6t3HXutmSCRAVSE5wm4Rdo7U4jpyeQvo3chGzlt15lhr5A2Ioslz7UpOJhTzl03dFi3Tan5CUH1wGabrncp5Lrfwls7T066sCp8cAi9h4l2B2W0wksuvFA6ZJ90YPG4bPOO58dMDHFubgMXXw5O3GK0DJx5OIydPDlQstqe01ylDmRwP476fZjY7sydHS4nHdstLjXt6HBWjJj9r1ufCMdQ9+gYDnFEAXc5a/dwwT9DBEE4vsApbmdmhg9Wgyf736aGPWLdFS77FlDt6NwuQOm3MaqX7KPE8gMv/VYu8dgd0SYSJUY6dv0NPJCeBmumIw11xidPbBR5ONT6y9hJfj1xdnF1dXF5+yP7Pri6PD6wyHVUTotGTUoQrO5Yd6KoXNSGHaiMdtrijiyoIqX1QT6HlZwxwavTXu/nMBHRhF9mOxWVeYi6vCdQlHPcnougcMA9hrb6CJnioYjQZ+m0FDoijxxgcTY+Bvp9BRKMC4+qiqQAElz9QgfFTs09JUKUH0RrtIM3M8JNmiGbOhJFeyfFM5grHfGuDOq2aL0xdn4MbxN+7OFLQiXDtbbHIC3OJihe1XkhtcTUilJ76rIWYnEynHSsaEHlYyu2vaJeg0UJZA/+5XZqaA4VWUID3VfW1e+ZuU7z7M1JBNF/NK8ReNMVe1UDByGavTD58NDA8uZVWiGexiPD+5/W5EDIoPxlsXx7xwrdiplcy18WOBVF4iByMqwomRjSiiaPuUj1J+wQmIY5mW57T0Ii5qM3QrFfpVMb06CNFZotqx0Nej97aFVe9e4PEQrsHL0OW/rEL6udIzs/o/dS1dvzb0oVlTmrD2mUyYYo1ddu2qadNxtHZgIBoVQZlsWe3CQYhDy5Y/Ghb6hQu1UJe8cedf8xSo7ah6bbkVmfblZ++7N8azX4ILNsVNMMq586tBr2DsGAi+wOdt7QqsPyYzjzp3QtdgtkzdeVHKNIQa3Rp3NsZM4G9vbGSPay7GZOXv+FK/5bZ/rl2WTQtummd0jzyrICSjvRoSs8MNPh+fXh0xstjn2k729tfecJQFhm2N7BAuRbIO+oysLMbzX/LyIRTx3tn7p/+IwO4GqyoYKfpv1wyY7Pt9PESzGD7KuePxjvWJ+w/nm3Tv3ugX2VwjezhgQfTr+ll1qi5ydRcsyxKj/r/U44g+MA9O2KHbordo2HI4PcVG6XqR5uNM22uOC7UbBObetXbxLMRkeehRj0J+gQu1QEyiCvfem1diC7UgN+3oUMRlF0MXXrysGHuLx6GRH6FStb1uwG6mU0oaraoO1HyMjFhVhsWcCsgZ4zvuiW19SdtB8T4FBU5AYGioqtmAT1KqQQYV8i9jECKTIXcsrfFMf8XLOlmyYyhvDoYzE4CYQbMAdxvpMuBM8TESMsZh6yoJf/ZqhPlIGbFmShdB9X02AknyHpcxU/Khj5BObCXFYkfWJra2+93xfu9DwjxSbbZ6aftk9wyJbrlP4su/umH1T/5ViWxovtWsoysuHKY1HoDN0bMluoC5KFTRXRmIb9xOWiqutbEjoWnTfXbpFAvTQWur7ul3+9tsEOrZRwbqoYwv2WRlUgL9v3MmVbCGal1UlJ8o3xCiozslnmdOIcyltbpmu8uPZpz9S4PUmCk4CASAhKgqZxodw4k+y1yhLTvnYuLvoFALGRNkztCjLIpi59XozTniKZ7xGyq10HUVpXcm3VsLxaHI6pabZz2bk+rVS7df6tnn13sUzZpvHx6YnqT80E18wWARDHwSLt+ipLqXYQnrdoH2OO1/H4yPOK9mGVIs8tK/wXFQJerstneFvBhXkDj36rOA7xf0jFOrJfg3FxfvjrSoY18MOlsFOegmO1ASJl1OVDBm67fEB77vv7T1kPAyhlVNprZIM3VYqeO3fd5u75p+ucXwMzVoqIUpxkEVBX6+lf6tfmJTbO/arNHFh8jJUhap7GDv1TQpF1K4McwJgPoXyhW8ZnjF03TcvNFWsskxBYB8QNf32bIVJqSrf7ulteuaN3zc/gV/9qJa94cD0dRXuvDKhY7vs2jXLzPXQbWDZ843RjdcSQAuXF+MbGzglg63dGHKUXiWMb2RZ9njTlSi2ZS7eVOgI2Z/XS9o3lm3dFMvol8k1NqvZRRH7JOSAOLVhfqRm+aSU2WvLbE22Z/aXWv+5qdPRga0YQ9t2klZXTICFviLLUcuyGBj/vBEEcZhMGcmaCBnHtK3JmeVblsGhNQ5px2goIVxHNYTjaaNjbgqmaEPzHuQMWlPyXkFeCTPNyQwbNpIRvNa8WLpXYStGd/ErLmgUQ2+mhHG9F2G8hA4DIcgZjw/cCtYY3t5hX+5qaPRFw+MYnTWW15Ro301coojRWMdgezecJny1r0/Xu2vBm/52noLJYrH7G4Ndsgj3M/C4TkI1E2CQ/ewAZ9kRx+hU9kfgW9kdy+5w7HAc0mjeVpmd36AIVWVIon95CrYfW7lZ1jDyInKz/OumuXU3UGPI90b9yNLWll3eQOcq9LUOYiAavWzYhOao2xBifz7sqRy6ay37ujHMZkJzdXddIh6d1a4mbTw8eLdovqNgdobDodqWxU43hQ37BHZN/zTfOZ7jv5gd4djzMHSwjCmFXd/AhLA3sV7Pxm7Ytm2n9pFeH2FbimZjN+5ZiMEOmEaEUNG/erlzpMPObdCFC1VNdkyy7MImGf/dJrm/MuIIiXgNu7NJmk/ltnbIXX2Tva9Z/CGFdxdrrPRq/vMJk+XO41mf6n6zzHzqdIwFImJfuJKV4t6SS16ZG9u+MQlMhZbIx0d7XoFj07eSPuPQdnH39PcZNqliz7cShkaoYhCTTcWObyU4hfSuuvP3HCtYs6ZgOcl4Yys2cWMdhlD/LE4yjPExV6rY4c21rZd26BSp2Nsth7lvfLTJ39ZORkmuFfu8uaRwq5JERLB3lq5y3bvGeYgx8paGGCNbh18lLGtnsUuWGPw6m70Vugi3vmbzzQ04ZsUub+zxFrjRtv5rxfZu9E9WcrDB8Wi0RmzipnOW1S4iCR5Db9ZrxdZukBUq3GWNDnECj2PoFfu+lVjn0BNm1jzi95bue9ndBxuqbPB3v3u3SYcTqmI7OBaRUiYJrlXsB5dXrB2kpz/rOr9A9bTJtdyKNcUr8AoZeNVtdto++8suVeF6kzA0ss2igQHkfK4x5GvB7fnsiIqlxitfKi5VdGM02qvCNR+B3WfsFMrmIwUUhOADGHuxKtYdB43bbSgxeLHi8UE6ZcVa5NalVU+vHWuGw3C0uU0aNVWsGQ7b0QRb4JXOWTKcxWLCgRpfzY/ReHXGaPo8bHDhAllT3ICVx2FeFqEUGDPaKpYbl0oURa62rb2bdDimb1YTl6yUNa3eVSwozgvK0tv1e816nh21NzeuJ1KMfm5/OHu6cjXFzWtv5+vOs5JoOFqSCB05tmNwr6HykXxh/HKsTA6GX6XRlIp1x3m7PRy0qIRrxTrivEsbOoxGVfYrFg0XlK3b7gDj7WFV5FKWocH0m1ZWsWwVoxSFZ41bL2Ll6lLB7tMh9eP4IB0cdWuqWKkKXCQPhUZfPfWVdHdjeDsz7URbMZcLhokIOuaonEXFPC5X0Fxuc9EhBNPxGa/oVUzqYgfBUAR0VBMpBkdyMMLGRk7FlDA24vIhrjh1OIJnm4e+XbPV04Mj1qkPv6U8xx9Oso6jCduE5mh46FaqWKbK6MlL5q/Yf/0f", BinaryEncoding.Base64), Compression.Deflate)),
				Rows = Table.FromRows(Source, {"artist_name", "track_id", "streams"}),
				Typed = Table.TransformColumnTypes(Rows, {{"artist_name", type text}, {"track_id", Int64.Type}, {"streams", Int64.Type}}, "en-US")
			in
				Typed

